src/accounts/urls.py
from django.conf.urls import url

from . import views

app_name = "accounts"

urlpatterns = [
	url(r"login/$", views.LoginView.as_view(), name="login"),
	url(r"logout/$", views.LogoutView.as_view(), name="logout"),
	url(r"signup/$", views.SignUpView.as_view(), name="signup"),
]

src/ecommuter/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import views


urlpatterns = [
    path('ecommuter_admin/', admin.site.urls),
    path('', views.AboutView.as_view(),name="home"),
    path('accounts/', include('accounts.urls', 'accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
]

urlpatterns += staticfiles_urlpatterns()
# Remove this conditional check if you want to upload to Heroku
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/accounts/models.py
from django.contrib.auth.models import (
	AbstractBaseUser,
	BaseUserManager,
	PermissionsMixin,
)
from django.conf import settings
from django.db import models
from django.utils import timezone


def upload_dir(self, filename):
    return "{}/{}".format(self.username, filename)


class UserManager(BaseUserManager):

	def create_user(self, email, username, mobile, display_name=None, password=None):
		'''
		Raising ValueError for the user model
		'''
		if not email:
			raise ValueError("Users must have an email address")
		if not mobile:
			raise ValueError("Users must have an mobile number")
		if not display_name:
			display_name = username

		'''
		Making a new user instance which is stored in memory only...
		'''
		user = self.model(
			email = self.normalize_email(email),
			username = username,
			mobile = mobile,
			display_name = display_name,
		)
		user.set_password(password)
		user.save()
		return user


	def create_superuser(self, email, username, mobile, display_name, password):
		'''
		Here we pass the create_user() method above to create super_user
		'''
		user = self.create_user(
			email,
			username,
			mobile,
			display_name,
			password,
		)
		user.is_staff = True
		user.is_superuser = True
		user.save()
		return user



class User(AbstractBaseUser, PermissionsMixin):
	email = models.EmailField(unique=True)
	username = models.CharField(max_length=40, unique=True)
	mobile = models.IntegerField(unique=True)
	display_name = models.CharField(max_length=150)
	bio = models.CharField(max_length=150, blank=True, default="")
	avatar = models.ImageField(blank=True, null=True, upload_to=upload_dir)
	date_joined = models.DateTimeField(default=timezone.now)
	is_active = models.BooleanField(default=True)
	is_staff = models.BooleanField(default=False)

	objects = UserManager()

	USERNAME_FIELD = "username"
	REQUIRED_FIELDS = ["email", "mobile", "display_name"]

	def __str__(self):
		return '@{}'.format(self.username)
	
	@property
	def image_url(self):
		if self.avatar:
			return self.avatar.url
		else:
			#return 'https://res.cloudinary.com/hwz12fud7/image/upload/v1538131159/media/musicadence/musicadence.jpg'
			return "static/img/faces/user.png"

	def get_short_name(self):
		return self.display_name

	def get_long_name(self):
		return '{} (@{})'.format(self.display_name, self.username)

src/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm#
from django.contrib.auth import get_user_model
#from django.contrib.auth.models import User



class UserCreateForm(UserCreationForm):
	class Meta:
		fields = ("username", "email", "mobile", "password1", "password2")
		model = get_user_model()

	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.fields["username"].widget.attrs.update({'placeholder': 'username'})
		self.fields["email"].widget.attrs.update({'placeholder': 'email@example.com'})
		self.fields["mobile"].widget.attrs.update({'placeholder': 'mobile'})
		self.fields["password1"].widget.attrs.update({'placeholder': 'password'})
		self.fields["password2"].widget.attrs.update({'placeholder': 'confirm password'})
		self.fields["password1"].help_text = ""
		self.fields["password2"].help_text = ""
		self.fields["username"].label = ""
		self.fields["email"].label = ""
		self.fields["mobile"].label = ""
		self.fields["password1"].label = ""
		self.fields["password2"].label = ""

src/accounts/views.py
from django.contrib.auth import login, logout
from django.shortcuts import render
from django.urls import reverse_lazy
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.views.generic import FormView, RedirectView, CreateView

from . import forms



class LoginView(FormView):
	form_class = AuthenticationForm
	success_url = reverse_lazy("home")
	template_name = "accounts/login.html"

	def get_form(self, form_class=None):
		if form_class is None:
			form_class = self.get_form_class()
		return form_class(self.request, **self.get_form_kwargs())

	def form_valid(self, form):
		login(self.request, form.get_user())
		return super().form_valid(form)


class LogoutView(RedirectView):
	url = reverse_lazy("home")

	def get(self, request, *args, **kwargs):
		logout(request)
		return super().get(self, request, *args, **kwargs)


class SignUpView(CreateView):
	form_class = forms.UserCreateForm
	success_url = reverse_lazy("login")
	template_name = "accounts/signup.html"

src/ecommuter/views.py
from django.views.generic import TemplateView

class AboutView(TemplateView):
    template_name = "base.html"

src/accounts/templates/accounts/login.html
{% extends "layout.html" %}
{% load crispy_forms_tags %}

{% block title %}Login{% endblock title %}

{% block content %}
<div class="section section-signin">
    
    <div class="image-container">
        <div class="filter filter-color-black"  style="background-image: url('../assets/img/header-9.jpeg')">
            <div class="col-md-8 col-md-offset-1">
                <div class="content">
                    <div class="title-area">
                        <h1 class="title-modern">Gaia</h1>
                        <h3>Ecommuter</h3>
                    </div>

                    <h5 class="subtitle">First Feature</h5>
                    <p>Ultralight Prayer: Happy Easter! In Roman times the artist would contemplate proportions and colors. Now there is only one important color...
                    </p>
                    <h5 class="subtitle">Second Feature</h5>
                    <p>We no longer have to be scared of the truth I promise I will never let the people down. I want a better life for all!
                    </p>
                    <h5 class="subtitle">Third Feature</h5>
                    <p>WI have a dream. That dreams will actualize. Dreams will manifest. When companies doubt me they doubt us.
                    </p>
                </div>
            </div>
        </div>
    </div>
    <form class="form-container" method="POST">
        {% csrf_token %}
        <div class="col-sm-6 col-sm-offset-3 col-xs-10 col-xs-offset-1 text-center">

            <div class="title-area">
                <h2>Welcome</h2>
                <div class="separator separator-danger">✻</div>
            </div>

            <!--<label><h4 class="text-gray">Your username</h4></label>-->
            <div class="form-group">
                {{form|crispy}}
                    <!--
                    <input type="password" name="password" value="" placeholder="&#x25CF;&#x25CF;&#x25CF;&#x25CF;" class="form-control form-control-plain">
                    -->
            </div>
            <p class="text-gray">
                By signing up you agree to<br>
                <a href="#">Terms of Use</a> and <a href="#"> Privacy Policy</a>
            </p>

            <div class="footer">
                <button class="btn btn-danger btn-round btn-fill btn-wd" type="submit">
                    login
                </button>
                <p class="text-gray info">Don't have an account? <a href="{% url 'accounts:signup' %}">Sign up</a></p>
            </div>
        </div>
    </div>
</div>
    
{% endblock content %}

src/accounts/templates/accounts/signup.html
{% extends "layout.html" %}
{% load crispy_forms_tags %}
{% block title %}SignUp{% endblock title %}
{% block content %}
<div class="section section-white section-signup">
    <div class="static-image">
        <div class="image"
            style="background-image: url('../static/img/header-4.jpeg')">
        </div>
        <div class="container">
            <div class="row">
                <div class="col-md-5 col-md-offset-3 text-center">
                    <h2 class="text-white">Sign up</h2>

                    <div class="separator separator-danger">✻</div>

                    <form method="POST">
                        {% csrf_token %}
                        <div class="form-group">
                            {{form|crispy}}
                        </div>
                        <p>
                            By signing up you agree to
                            <a href="#">
                                <span class="text-danger">
                                    Terms of Service
                                </span>
                            </a> and
                            <a href="#">
                                <span class="text-danger" >
                                    Privacy Policy
                                </span>
                            </a>
                        </p>
                        <div class="button-signin">
                            <button class="btn btn-danger btn-round btn-fill btn-wd" type="submit">
                                Sign Up
                            </button>
                        </div>
                        <p>
                            Or use an existing <a href="{% url 'accounts:login' %}" class="text-danger">account</a>.
                        </p>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

src/templates/base.html
{% extends 'layout.html' %}
{% load static %}

{% block title %}About{% endblock title %}

{% block content %}
<div class="section section-header section-header-about">
    <div class="parallax filter filter-color-black">
        <div class="image"
            style="background-image:url({% static '/img/header-12.jpeg'  %})">
        </div>
        <div class="container">
            <div class="content">
                <h1>About Ecommuter</h1>
                <h3 class="subtitle">How We Started the Journey.</h3>
            </div>
        </div>
    </div>
</div>

<div class="section">
    <div class="text-area">
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <div class="title-area">
                        <h5 class="subtitle text-gray">Est. 2013</h5>
                        <h2>Who we are section</h2>
                        <div class="separator separator-danger">✻</div>
                    </div>
                </div>
                <div class="col-md-7 col-md-offset-1">
                    <div class="description">
                        <p>That dreams will actualize. Dreams will manifest. I stand with the utmost humility. We are so blessed! All praises and blessings to the families of people who never gave up on dreams I speak truth to power!</p>
                        <p>We can't wait to work with you because you will love to work with us.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="text-center">
                <div class="col-md-10 col-md-offset-1">
                    <div class="row">
                        <div class="col-md-5 col-md-offset-1">
                            <div class="card card-plain">
                                <img alt="..." src="{% static '/img/office-1.jpeg' %}" />
                            </div>
                            <div class="card card-plain">
                                <img alt="..." src="{% static '/img/office-3.jpeg' %}" />
                            </div>
                        </div>
                        <div class="col-md-5">
                            <div class="card card-plain">
                                <img alt="..." src="{% static '/img/project-5.jpg' %}" />
                            </div>
                            <div class="card card-plain">
                                <img alt="..." src="{% static '/img/office-4.jpeg' %}" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="section">
    <div class="container">
        <div class="row">
            <div class="title-area">
                <h2>Our Services</h2>
                <div class="separator separator-danger">✻</div>
                <p class="description">We promise you a new look and more importantly, a new attitude. We build that by getting to know you, your needs and creating the best looking clothes.</p>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3 col-sm-6">
                <div class="info-icon">
                    <div class="icon text-danger">
                        <i class="pe-7s-car"></i>
                    </div>
                    <h3>Delivery</h3>
                    <p class="description">We sketch your wardrobe down to the last detail and present it to you.</p>
                </div>
            </div>
            <div class="col-md-3 col-sm-6">
                <div class="info-icon">
                    <div class="icon text-danger">
                        <i class="pe-7s-graph1"></i>
                    </div>
                    <h3>Sales</h3>
                    <p class="description">We make our design perfect for you. Our adjustment turn our clothes into your clothes.</p>
                </div>
            </div>
            <div class="col-md-3 col-sm-6">
                <div class="info-icon">
                    <div class="icon text-danger">
                        <i class="pe-7s-note2"></i>
                    </div>
                    <h3>Content</h3>
                    <p class="description">We create a persona regarding the multiple wardrobe accessories that we provide..</p>
                </div>
            </div>
            <div class="col-md-3 col-sm-6">
                <div class="info-icon">
                    <div class="icon text-danger">
                        <i class="pe-7s-music"></i>
                    </div>
                    <h3>Music</h3>
                    <p class="description">We like to present the world with our work, so we make sure we spread the word regarding our clothes.</p>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="section section-our-team">
    <div class="container">
        <div class="text-area">
            <div class="title-area">
                <h2>Collaborators</h2>
                <div class="separator separator-danger">✻</div>
                <p class="description">There are two me's when I take a picture. As Wolf I take pictures to be sold and as Bear all of them are free of charge, take his as a philanthropist.</p>
            </div>
        </div>
        <div class="team">
            <div class="row">
                <div class="col-md-10 col-md-offset-1">
                    <div class="row">
                        <div class="col-md-4">
                            <div class="card card-member card-plain">
                                <div class="content">
                                    <div class="avatar avatar-danger">
                                        <img alt="..." class="img-circle" src="{% static '/img/faces/face_1.jpg' %}" />
                                    </div>
                                    <div class="description">
                                        <h3 class="big-text">Tina</h3>
                                        <p class="small-text">Web designer @CreativeTim</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="card card-member card-plain">
                                <div class="content">
                                    <div class="avatar avatar-danger">
                                        <img alt="..." class="img-circle" src="{% static '/img/faces/face_4.jpg' %}" />
                                    </div>
                                    <div class="description">
                                        <h3 class="big-text">Mike</h3>
                                        <p class="small-text">Marketing @Shopify</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="card card-member card-plain">
                                <div class="content">
                                    <div class="avatar avatar-danger">
                                        <img alt="..." class="img-circle" src="{% static '/img/faces/face_3.jpg' %}" />
                                    </div>
                                    <div class="description">
                                        <h3 class="big-text">Rosa</h3>
                                        <p class="small-text">Product Designer @Xerox</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="card card-member card-plain">
                                <div class="content">
                                    <div class="avatar avatar-danger">
                                        <img alt="..." class="img-circle" src="{% static '/img/faces/face_5.jpg' %}" />
                                    </div>
                                    <div class="description">
                                        <h3 class="big-text">Tony</h3>
                                        <p class="small-text">Hacker @Canon</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="card card-member card-plain">
                                <div class="content">
                                    <div class="avatar avatar-danger">
                                        <img alt="..." class="img-circle" src="{% static '/img/faces/face_2.jpg' %}" />
                                    </div>
                                    <div class="description">
                                        <h3 class="big-text">Northon</h3>
                                        <p class="small-text">Happiness Hero @Nikon</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="card card-member card-plain">
                                <div class="content">
                                    <div class="avatar avatar-danger">
                                        <img alt="..." class="img-circle" src="{% static '/img/faces/face_6.jpg' %}" />
                                    </div>
                                    <div class="description">
                                        <h3 class="big-text">Bear</h3>
                                        <p class="small-text">Just a friend</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- end team -->
    </div>
</div>
{% endblock content %}

src/templates/footer.html

<footer class="footer footer-big footer-color-black" data-color="black">
        <div class="container">
            <div class="row">
                <div class="col-md-2 col-sm-3">
                    <div class="info">
                        <h5 class="title">Company</h5>
                        <nav>
                            <ul>
                                <li>
                                    <a href="#">Home</a></li>
                                <li>
                                    <a href="#">Find offers</a>
                                </li>
                                <li>
                                    <a href="#">Discover Projects</a>
                                </li>
                                <li>
                                    <a href="#">Our Portfolio</a>
                                </li>
                                <li>
                                    <a href="#">About Us</a>
                                </li>
                            </ul>
                        </nav>
                    </div>
                </div>
                <div class="col-md-3 col-md-offset-1 col-sm-3">
                    <div class="info">
                        <h5 class="title"> Help and Support</h5>
                        <nav>
                            <ul>
                                <li>
                                    <a href="#">Contact Us</a>
                                </li>
                                <li>
                                    <a href="#">How it works</a>
                                </li>
                                <li>
                                    <a href="#">Terms &amp; Conditions</a>
                                </li>
                                <li>
                                    <a href="#">Company Policy</a>
                                </li>
                                <li>
                                    <a href="#">Money Back</a>
                                </li>
                            </ul>
                        </nav>
                    </div>
                </div>
                <div class="col-md-3 col-sm-3">
                    <div class="info">
                        <h5 class="title">Latest News</h5>
                        <nav>
                            <ul>
                                <li>
                                    <a href="#">
                                        <i class="fa fa-twitter"></i> <b>Get Shit Done</b> The best kit in the market is here, just give it a try and let us...
                                        <hr class="hr-small">
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <i class="fa fa-twitter"></i> We've just been featured on <b> Awwwards Website</b>! Thank you everybody for...
                                    </a>
                                </li>
                            </ul>
                        </nav>
                    </div>
                </div>
                <div class="col-md-2 col-md-offset-1 col-sm-3">
                    <div class="info">
                        <h5 class="title">Follow us on</h5>
                        <nav>
                            <ul>
                                <li>
                                    <a href="#" class="btn btn-social btn-facebook btn-simple">
                                        <i class="fa fa-facebook-square"></i> Facebook
                                    </a>
                                </li>
                                <li>
                                    <a href="#" class="btn btn-social btn-dribbble btn-simple">
                                        <i class="fa fa-dribbble"></i> Dribbble
                                    </a>
                                </li>
                                <li>
                                    <a href="#" class="btn btn-social btn-twitter btn-simple">
                                        <i class="fa fa-twitter"></i> Twitter
                                    </a>
                                </li>
                                <li>
                                    <a href="#" class="btn btn-social btn-reddit btn-simple">
                                        <i class="fa fa-google-plus-square"></i> Google+
                                    </a>
                                </li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
            <hr>
            <div class="copyright">
                ©
                <script>
                    document.write(new Date().getFullYear())
                </script> Geetech Lab, made with love
            </div>
        </div>
    </footer>

src/templates/layout.html

<!--

=========================================================
* Gaia Bootstrap Template PRO - v1.0.1
=========================================================

* Product Page: https://www.geetechlab.com
* Copyright 2019 geetech lab (https://www.geetechlab.com)

* Coded by Creative geetech

=========================================================

* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

-->

{% load static %}


<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="utf-8" />
        <link rel="apple-touch-icon" sizes="76x76" href="{% static /img/apple-icon.png">
        <link rel="icon" type="image/png" sizes="96x96" href="{% static /img/favicon.png">

        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

        <title>{% block title %}{% endblock title %} | Ecommuter</title>
        <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
        <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" />
        <link href="{% static 'css/gaia.css' %}" rel="stylesheet"/>

        <!-- Canonical SEO -->
        <link rel="canonical" href="https://www.creative-tim.com/product/gaia-bootstrap-template-pro"/>

        <!--     Fonts and icons     -->
        <link href='https://fonts.googleapis.com/css?family=Cambo|Lato:400,700' rel='stylesheet' type='text/css'>
        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
        <link href="{% static 'css/fonts/pe-icon-7-stroke.css' %}" rel="stylesheet">

    </head>

    <body>

        {% include "navbar.html" %}


        {% block content %}
        {% endblock content %}


        {% include "footer.html" %}

    </body>

<!--   core js files    -->
<script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/bootstrap.js' %}" type="text/javascript"></script>

<!--  js library for devices recognition -->
<script type="text/javascript" src="{% static 'js/modernizr.js' %}"></script>

<!--  script for google maps   -->
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js"></script>

<!--   file where we handle all the script from the Gaia - Bootstrap Template   -->
<script type="text/javascript" src="{% static 'js/gaia.js'  %}"></script>


</html>

src/templates/navbar.html
<nav class="navbar navbar-default navbar-transparent navbar-fixed-top" color-on-scroll="200">
        <!-- if you want to keep the navbar hidden you can add this class to the navbar "navbar-burger"-->
        <div class="container">
            <div class="navbar-header">
                <button id="menu-toggle" type="button" class="navbar-toggle" data-toggle="collapse" data-target="#example">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar bar1"></span>
                    <span class="icon-bar bar2"></span>
                    <span class="icon-bar bar3"></span>
                </button>
                <a href="https://www.ecommuter.com.ng" class="navbar-brand">
                    Ecommuter
                </a>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav navbar-right navbar-uppercase">
                    <li>
                        <a href="{% url 'home' %}">Home</a>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Accounts<span class="caret"></span></a>
                        <ul class="dropdown-menu dropdown-danger">
                            <li>
                                <a href="{% url "accounts:login" %}">Login</a>
                            </li>
                            <li>
                                <a href="{% url "accounts:signup" %}">SignUp</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="#">Contact-us</a>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="fa fa-share-alt"></i> Share
                        </a>
                        <ul class="dropdown-menu dropdown-danger">
                            <li>
                                <a id="facebookNav" href="#"><i class="fa fa-facebook-square"></i> Facebook</a>
                            </li>
                            <li>
                                <a id="twitterNav" href="#"><i class="fa fa-twitter"></i> Twitter</a>
                            </li>
                            <li>
                                <a id="googleNav" href="#"><i class="fa fa-google-plus"></i> Google</a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
    </nav>